substitutions:
  name: mtr1
  friendly_name: MTR1
  device_description: Apollo MTR-1 - version ${version}.

packages:
  ApolloAutomation.MTR-1:
    url: https://github.com/ApolloAutomation/MTR-1
    files: Integrations/ESPHome/MTR-1.yaml
    ref: main
    refresh: 1s

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: Apollo MTR-1
  name_add_mac_suffix: false

api:
  encryption:
    key: !secret mtr1-api-key

ota:
  - platform: esphome
    password: !secret mtr1-ota-key

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      hidden: true
  domain: .mydomain.taco

mdns:
  disabled: true